# Generated by Django 3.1.7 on 2021-05-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udachi', '0009_otzivi'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalizakaza',
            name='kolvo',
            field=models.FloatField(default=1, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='otzivi',
            name='data_otziva',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='otzivi',
            name='telephone_avtora',
            field=models.CharField(max_length=255, verbose_name='Телефон автора'),
        ),
    ]
