# Generated by Django 3.1.7 on 2021-05-05 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('udachi', '0010_auto_20210505_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zayavka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('status', models.IntegerField(choices=[(1, 'Не Выполнено'), (2, 'Выполнено')], default=1, verbose_name='Тип операции')),
                ('ispolnitel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('postavshik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='udachi.postavshiki', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='DetaliZayavki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolvo', models.FloatField(default=1, verbose_name='Кол-во')),
                ('ingridient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='udachi.ingridienti', verbose_name='Ингридиент')),
                ('sklad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='udachi.sklad', verbose_name='Склад')),
                ('zayavka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='udachi.zayavka', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Деталь Заявки',
                'verbose_name_plural': 'Детали Заявки',
            },
        ),
    ]
