# Generated by Django 3.1.7 on 2021-05-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udachi', '0011_detalizayavki_zayavka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bronirovanie',
            name='vremia',
        ),
        migrations.AlterField(
            model_name='bronirovanie',
            name='data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата'),
        ),
    ]
