# Generated by Django 3.1.7 on 2021-05-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udachi', '0012_auto_20210516_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='bronirovanie',
            name='kolvo_gostei',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество гостей'),
        ),
    ]
