# Generated by Django 3.1.7 on 2021-05-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udachi', '0015_auto_20210521_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalizayavki',
            name='ediz',
            field=models.IntegerField(choices=[(1, 'шт'), (2, 'кг'), (3, 'л')], default=1, verbose_name='Единица измерения'),
        ),
    ]
