# Generated by Django 3.1.7 on 2021-05-30 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('udachi', '0016_detalizayavki_ediz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zakaz',
            name='stolik',
        ),
        migrations.AlterField(
            model_name='detalizayavki',
            name='zayavka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detali_po_zaiavki', to='udachi.zayavka', verbose_name='Заявка'),
        ),
    ]
