# Generated by Django 3.1.7 on 2021-05-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udachi', '0018_auto_20210531_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='bronirovanie',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Бронирование'),
        ),
    ]
